-- Migration: Create reports table for storing AMY report interpretations
-- Description: This table stores the short interpretations and scores generated by AMY
-- Date: 2024-12-04

-- Create reports table
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assessment_id UUID NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  score_numeric INTEGER,
  sleep_score INTEGER,
  risk_level TEXT CHECK (risk_level IN ('low', 'moderate', 'high')),
  report_text_short TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index on assessment_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_reports_assessment_id ON reports(assessment_id);

-- Create index on created_at for faster sorting
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);

-- Create trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_reports_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW
  EXECUTE FUNCTION update_reports_updated_at();

-- Add comment to table
COMMENT ON TABLE reports IS 'Stores AMY-generated stress and sleep report interpretations with scores';
COMMENT ON COLUMN reports.id IS 'Primary key - unique report identifier';
COMMENT ON COLUMN reports.assessment_id IS 'Foreign key to assessments table';
COMMENT ON COLUMN reports.score_numeric IS 'Stress score (0-100)';
COMMENT ON COLUMN reports.sleep_score IS 'Sleep score (0-100)';
COMMENT ON COLUMN reports.risk_level IS 'Stress risk level: low, moderate, or high';
COMMENT ON COLUMN reports.report_text_short IS 'Short interpretation text generated by AMY';
COMMENT ON COLUMN reports.created_at IS 'Timestamp when the report was created';
COMMENT ON COLUMN reports.updated_at IS 'Timestamp when the report was last updated';
