// This file is auto-generated by Supabase CLI
// DO NOT EDIT MANUALLY - Run `npm run db:typegen` to regenerate
//
// Generated types represent the exact database schema from Supabase
// If this file is out of sync with your database, CI will fail

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      // Types will be generated here by Supabase CLI
      [key: string]: unknown
    }
    Views: {
      [key: string]: unknown
    }
    Functions: {
      [key: string]: unknown
    }
    Enums: {
      [key: string]: unknown
    }
  }
}
