// This file is auto-generated by Supabase CLI
// DO NOT EDIT MANUALLY - Run `npm run db:typegen` to regenerate
//
// Generated types represent the exact database schema from Supabase
// If this file is out of sync with your database, CI will fail
//
// To regenerate:
//   1. Ensure Supabase is running: supabase start
//   2. Run: npm run db:typegen
//   3. Commit the updated file

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      // Note: This is a placeholder file
      // Run `npm run db:typegen` after applying migrations to generate actual types
      // The CI workflow will enforce that types stay in sync with the schema
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>
        Returns: unknown
      }
    }
    Enums: {
      [key: string]: string
    }
  }
}

